<a href="https://colab.research.google.com/github/ktp2gx/2002DS/blob/main/Basketball_Hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

acc_players_df = pd.read_csv('/content/acc_players-2324F.csv')

acc_players_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Totals,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Shooting,Unnamed: 15,Unnamed: 16,Unnamed: 17,Advanced,Unnamed: 19,Unnamed: 20
0,Rk,Player,Class,Pos,School,G,MP,TRB,AST,STL,...,TOV,PF,PTS,FG%,2P%,3P%,FT%,PER,WS,BPM
1,1,Amaree Abram,SO,G,Georgia Tech,10,108,17,11,1,...,9,10,34,0.262,0.318,0.2,0.615,4.1,-0.1,-6.4
2,2,Sola Adebisi,FR,F,Florida State,7,9,1,1,0,...,1,1,2,0.5,0.5,NaN,NaN,3.5,0,-6.7
3,3,Prince Aligbe,SO,F,Boston College,35,651,119,21,15,...,30,51,164,0.435,0.522,0.147,0.62,9.4,0.9,-1.3
4,4,Abe Atiyeh,SR,G,Boston College,4,6,0,0,0,...,1,0,3,0.333,0,1,NaN,1.1,0,-8.2

In [9]:
acc_players_df.columns = acc_players_df.iloc[0]
acc_players_df = acc_players_df.drop(0).reset_index(drop=True)
acc_players_df.head()

,Rk,Player,Class,Pos,School,G,MP,TRB,AST,STL,...,TOV,PF,PTS,FG%,2P%,3P%,FT%,PER,WS,BPM
0,1,Amaree Abram,SO,G,Georgia Tech,10,108,17,11,1,...,9,10,34,0.262,0.318,0.2,0.615,4.1,-0.1,-6.4
1,2,Sola Adebisi,FR,F,Florida State,7,9,1,1,0,...,1,1,2,0.5,0.5,NaN,NaN,3.5,0,-6.7
2,3,Prince Aligbe,SO,F,Boston College,35,651,119,21,15,...,30,51,164,0.435,0.522,0.147,0.62,9.4,0.9,-1.3
3,4,Abe Atiyeh,SR,G,Boston College,4,6,0,0,0,...,1,0,3,0.333,0,1,NaN,1.1,0,-8.2
4,5,Zack Austin,JR,F,Pittsburgh,33,746,137,29,32,...,13,35,216,0.417,0.563,0.295,0.737,18,2.9,7.9

In [39]:
#2 Calculate the total points scored by all players combined

acc_total_PTS = acc_players_df['PTS'].sum()
print(acc_total_PTS)

38411

In [14]:
#2 Find the player who has played the most minutes (MP)
most_minutes_player = acc_players_df.loc[acc_players_df['MP'].idxmax()]['Player']
print(most_minutes_player)

Ian Schieffelin

In [18]:
#2 Identify the top 5 players in terms of total rebounds (TRB)
acc_players_df['TRB'] = pd.to_numeric(acc_players_df['TRB'])

top_5_rebounds = acc_players_df.nlargest(5, 'TRB')['Player']
print(top_5_rebounds)

5        Armando Bacot
178    Ian Schieffelin
90     Harrison Ingram
44      Mohamed Diarra
149      Norchad Omier
Name: Player, dtype: object

In [20]:
#3 Create a new DataFrame containing only players who played more than 500 minutes.
acc_players_df['MP'] = pd.to_numeric(acc_players_df['MP'])
playing_players_df = acc_players_df[acc_players_df['MP'] > 500]
print(playing_players_df)

0     Rk            Player Class Pos          School   G    MP  TRB  AST STL  \
2      3     Prince Aligbe    SO   F  Boston College  35   651  119   21  15
4      5       Zack Austin    JR   F      Pittsburgh  33   746  137   29  32
5      6     Armando Bacot    SR   F  North Carolina  37  1123  380   56  22
7      8     Reece Beekman    SR   G        Virginia  34  1114  124  212  68
9     10        Chris Bell    SO   F        Syracuse  32   865   75   21  18
..   ...               ...   ...  ..             ...  ..   ...  ...  ...  ..
203  204     Jamir Watkins    JR   F   Florida State  33   928  199   91  64
206  207         Tre White    SO   G      Louisville  29   907  170   39  24
207  208  Chauncey Wiggins    SO   F         Clemson  36   639   76   33   6
209  210   Curtis Williams    FR   G      Louisville  32   564   42   20  12
215  216    Jaeden Zackery    JR   G  Boston College  36  1216  119  152  63

0    ... TOV   PF  PTS    FG%    2P%    3P%    FT%   PER    WS   BPM
2    ...  30   51  164  0.435  0.522  0.147   0.62   9.4   0.9  -1.3
4    ...  13   35  216  0.417  0.563  0.295  0.737    18   2.9   7.9
5    ...  60  100  538   0.54  0.544    0.4  0.781  24.6   6.1   8.9
7    ...  70   43  486  0.443  0.487   0.31  0.754  23.4   4.9  10.5
9    ...  26   58  384  0.434  0.459   0.42  0.842  14.9   2.2   3.3
..   ...  ..  ...  ...    ...    ...    ...    ...   ...   ...   ...
203  ...  84   92  514  0.457    0.5  0.344  0.795  24.2   3.9   9.1
206  ...  53   66  357  0.456  0.515  0.299  0.752    15   1.7   1.8
207  ...  26   46  196  0.442  0.528  0.349  0.714    11   1.2   1.9
209  ...  26   24  170  0.317  0.373  0.287  0.714   5.9  -0.2  -3.8
215  ...  71   78  408  0.484  0.511  0.405  0.824  16.4   3.7   3.5

[98 rows x 21 columns]

In [23]:
#3 player with the highest total assists (AST).
highest_assists = playing_players_df.loc[playing_players_df['AST'].idxmax()]['Player']
print(highest_assists)

Jalen Warley

In [34]:
#3 Top 3 Assist Leads in the League
playing_players_df['AST'] = pd.to_numeric(playing_players_df['AST'])
top_3_assists = playing_players_df.sort_values(by='AST', ascending=False).head(3)['Player']
print(top_3_assists)

135    Casey Morsell
81          DJ Horne
42          RJ Davis
Name: Player, dtype: object

<ipython-input-34-2b474c032b9f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_players_df['AST'] = pd.to_numeric(playing_players_df['AST'])

In [35]:
#3 Top 3 Shot Blockers
playing_players_df['STL'] = pd.to_numeric(playing_players_df['STL'])
top_3_shot_blockers = playing_players_df.sort_values(by='STL', ascending=False).head(3)['Player']
print(top_3_shot_blockers)

16       Maliq Brown
7      Reece Beekman
132      Judah Mintz
Name: Player, dtype: object

<ipython-input-35-220c2e1de3f3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_players_df['STL'] = pd.to_numeric(playing_players_df['STL'])

In [29]:
#4 Group the players by School and calculate the total points scored by each school.
acc_players_df['PTS'] = pd.to_numeric(acc_players_df['PTS'])
school_points = acc_players_df.groupby('School')['PTS'].sum()
print(school_points)

School
Boston College    2667
Clemson           2785
Duke              2830
Florida State     2526
Georgia Tech      2272
Louisville        2304
Miami (FL)        2424
NC State          3101
North Carolina    3032
Notre Dame        2113
Pittsburgh        2495
Syracuse          2442
Virginia          2140
Virginia Tech     2547
Wake Forest       2733
Name: PTS, dtype: int64

In [30]:
#4 Group the players by School and calculate the total assists (AST) for each team
school_assists = acc_players_df.groupby('School')['AST'].sum()
print(school_assists)

School
Boston College       2100117204350459310003152
Clemson              2635105285171164600608033
Duke                  013100582683651180114730
Florida State     1801673321263300467015109291
Georgia Tech          112218224135593280284091
Louisville               870733471095031413920
Miami (FL)               804876711003388961518
NC State          1172484025670130111010055102
North Carolina        561501291380000443272113
Notre Dame          15214303310340182020029317
Pittsburgh              2913636123326076110930
Syracuse                2159108915111420603122
Virginia               21215122662133154929901
Virginia Tech        3826487361844148243300218
Wake Forest            15110218441321247440860
Name: AST, dtype: object

In [31]:
#4 Sort the schools by total points scored and display the top 3 schools
top_3_schools = school_points.nlargest(3)
print(top_3_schools)

School
NC State          3101
North Carolina    3032
Duke              2830
Name: PTS, dtype: int64